# Site settings
email: alfmarmil@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: AlfredoMM
description:
url: "alfredomariamilano.github.io"
twitter_username: alfmarmil
default_img:

# Profile settings
name: Alfredo Maria Milano
profile_img:
profile:
social:
  github: github.com/alfredomariamilano

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
