# Site settings
email: alfmarmil@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: alfredo maria milano
description: My personal portfolio
url: "http://alfredomariamilano.github.io"
twitter_username: alfmarmil
default_img:

# Profile settings
name: Alfredo Maria Milano
profile_img: https://avatars0.githubusercontent.com/u/20406650?v=3&s=466
profile:
social:
  github: http://github.com/alfredomariamilano

# Build settings
include: ["_categories", "_about"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
