# Site settings
email: alfmarmil@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: alfredo maria milano
description: My portfolio
url: "https://alfredomariamilano.github.io"
twitter_username: alfmarmil
default_img:

# Profile settings
name: Alfredo Maria Milano
profile_img: https://avatars0.githubusercontent.com/u/20406650?v=3&s=466
profile:   As an avid internet user, I developed an increasing interest on how things work in the web. This led me to study using online platforms and then to enroll in a Java course, while still having a full-time job. After realizing I was really enjoying programming, I decided to join a coding bootcamp to develop my skills in programming and start a new life, doing something that I really enjoy.
social:
  github: https://github.com/alfredomariamilano

# Build settings
include: ["_categories", "_about"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
